Data classes
fvlieshout/ATCS_group1 pull request #21
Opened 2021-05-15 14:23 UTC by MatPrst

Implementation of ```Data```, ```R8Data```, ```R52Data```, ```AGNewsData```, and ```IMDbData``` classes.
The implementation of  ```AGNewsData``` and  ```IMDbData``` are the exact same, so I have a commit that is not pushed yet with a superclass from which they both inherit. I'm not sure if that makes things too complicated or not.

2021-05-15 14:52 UTC, Matyasch requested changes
The way you get text for docs in reuters should be changed otherwise it looks good to me

2021-05-15 14:52 UTC, Matyasch commented on data_prep/reuters_data.py
> +            text = ' '.join(reuters.words(doc))
use `reuters.raw(doc)` instead as "Matthias." and "Matthias ." is different according to Roberta (and it's also much nicer)

2021-05-15 17:22 UTC, RedHilarious approved these changes
Looks good to me

2021-05-15 17:22 UTC, RedHilarious commented on data_prep/imdb_data.py
> +    def num_classes(self):
I guess if we have that here, we actually really don't need it in the `Dataset` classes

2021-05-16 08:06 UTC, Matyasch approved these changes
Looks good

2021-05-16 08:34 UTC, merged