PEP8 reformatting and removing not needed files.
fvlieshout/ATCS_group1 pull request #24
Opened 2021-05-16 13:06 UTC by RedHilarious

Some reformatting according to PEP8 and removing leftover files.

2021-05-16 14:05 UTC, fvlieshout requested changes
Most of it looks good.
For the graph_train.py: I think we should keep the code to resume training from a certain checkpoint and the corresponding argument ('--resume'). The other arguments can be thrown away

2021-05-16 14:05 UTC, fvlieshout commented on data_prep/agnews_data.py
>  from data_prep.data import HuggingFaceData
What's with the commented stuff?

2021-05-16 14:05 UTC, fvlieshout commented on graph_train.py
> -
It would be nice to have these line above to be able to continue from a checkpoint also in train.py

2021-05-16 14:05 UTC, fvlieshout commented on graph_train.py
> -    parser.add_argument('--resume', default=None, type=str, metavar='PATH',
Would be nice to keep this parameter to be able to resume from a checkpoint. The other arguments can be thrown away.

2021-05-16 19:25 UTC, RedHilarious commented on data_prep/agnews_data.py
>  from data_prep.data import HuggingFaceData
Not sure, came from @MatPrst. Notified / asked him about it

2021-05-16 21:26 UTC, MatPrst commented on data_prep/agnews_data.py
>  from data_prep.data import HuggingFaceData
Not sure why this is there. It can be removed since ```HuggingFaceData``` implements everything

2021-05-16 23:19 UTC, RedHilarious commented
@fvlieshout Worked on this, pls check again. If you feel ok with it, you can directly merge it.

2021-05-17 08:32 UTC, fvlieshout approved these changes
Nice!

2021-05-17 08:32 UTC, merged